from django.core.management.base import BaseCommand
from WineLabsApp.models import Wine


class Command(BaseCommand):
    help = 'Populate the database with wine data'

    def handle(self, *args, **kwargs):
        wines_data = [
            {'name': 'Mourvèdre', 'type': 'Red',
             'description': 'A bold red wine with flavors of black fruit, spice, and earth.'},
            {'name': 'Tokaji', 'type': 'Sweet',
             'description': 'A Hungarian sweet wine with flavors of apricot, honey, and botrytis.'},
            {'name': 'Prosecco', 'type': 'Sparkling',
             'description': 'An Italian sparkling wine with flavors of apple, pear, and citrus.'},
            {'name': 'Carignan', 'type': 'Red',
             'description': 'A medium-bodied red wine with flavors of red fruit, spice, and herbs.'},
            {'name': 'Muscadet', 'type': 'White',
             'description': 'A French white wine with flavors of citrus, green apple, and mineral.'},
            {'name': 'Sémillon', 'type': 'White',
             'description': 'A versatile white wine with flavors of citrus, pear, and honey.'},
            {'name': 'Blaufränkisch', 'type': 'Red',
             'description': 'An Austrian red wine with flavors of black cherry, spice, and herbs.'},
            {'name': 'Picpoul Blanc', 'type': 'White',
             'description': 'A French white wine with flavors of citrus, pear, and floral notes.'},
            {'name': 'Garnacha Blanca', 'type': 'White',
             'description': 'A Spanish white wine with flavors of citrus, peach, and floral notes.'},
            {'name': 'Grenache Blanc', 'type': 'White',
             'description': 'A white wine with flavors of citrus, peach, and mineral.'},
            {'name': 'Petite Sirah', 'type': 'Red',
             'description': 'A bold red wine with flavors of blackberry, plum, and pepper.'},
            {'name': 'Cabernet Sauvignon', 'type': 'Red',
             'description': 'A full-bodied red wine with flavors of black currant, cedar, and vanilla.'},
            {'name': 'Chardonnay', 'type': 'White',
             'description': 'A popular white wine with flavors of apple, butter, and oak.'},
            {'name': 'Merlot', 'type': 'Red',
             'description': 'A medium-bodied red wine with flavors of plum, cherry, and chocolate.'},
            {'name': 'Riesling', 'type': 'White',
             'description': 'A versatile white wine with flavors ranging from sweet to dry, often with notes of apricot, peach, and petrol.'},
            {'name': 'Pinot Noir', 'type': 'Red',
             'description': 'A delicate red wine with flavors of red berries, mushrooms, and earth.'},
            {'name': 'Sauvignon Blanc', 'type': 'White',
             'description': 'A crisp white wine with flavors of citrus, grass, and tropical fruits.'},
            {'name': 'Syrah/Shiraz', 'type': 'Red',
             'description': 'A bold red wine with flavors of blackberry, pepper, and smoked meat.'},
            {'name': 'Zinfandel', 'type': 'Red',
             'description': 'A robust red wine with flavors of dark berries, spice, and pepper.'},
            {'name': 'Malbec', 'type': 'Red',
             'description': 'A rich red wine with flavors of black cherry, plum, and chocolate.'},
            {'name': 'Viognier', 'type': 'White',
             'description': 'A floral white wine with flavors of peach, apricot, and honey.'},
            {'name': 'Chenin Blanc', 'type': 'White',
             'description': 'A versatile white wine with flavors ranging from dry to sweet, often with notes of apple, pear, and honey.'},
            {'name': 'Tempranillo', 'type': 'Red',
             'description': 'A Spanish red wine with flavors of red fruit, leather, and tobacco.'},
            {'name': 'Malvasia', 'type': 'White',
             'description': 'A sweet white wine with flavors of apricot, orange blossom, and honey.'},
            {'name': 'Carménère', 'type': 'Red',
             'description': 'A Chilean red wine with flavors of red berries, bell pepper, and spice.'},
            {'name': 'Gewürztraminer', 'type': 'White',
             'description': 'A aromatic white wine with flavors of lychee, rose petal, and spice.'},
            {'name': 'Montepulciano', 'type': 'Red',
             'description': 'An Italian red wine with flavors of dark berries, earth, and herbs.'},
            {'name': 'Albariño', 'type': 'White',
             'description': 'A Spanish white wine with flavors of citrus, peach, and saline minerality.'},
            {'name': 'Glera', 'type': 'Sparkling',
             'description': 'The grape used to make Prosecco, with flavors of apple, pear, and floral notes.'},
            {'name': 'Cava', 'type': 'Sparkling',
             'description': 'A Spanish sparkling wine made in the traditional method, with flavors of apple, citrus, and toast.'},
            {'name': 'Gamay', 'type': 'Red',
             'description': 'A light-bodied red wine with flavors of red berries, violet, and earth.'},
            {'name': 'Vermentino', 'type': 'White',
             'description': 'An Italian white wine with flavors of citrus, green apple, and herbs.'},
            {'name': 'Tannat', 'type': 'Red',
             'description': 'A bold red wine with flavors of blackberry, chocolate, and spice.'},
            {'name': 'Marsanne', 'type': 'White',
             'description': 'A French white wine with flavors of pear, almond, and wax.'},
            {'name': 'Moscato', 'type': 'Sweet',
             'description': 'A sweet white wine with flavors of peach, orange blossom, and musk.'},
            {'name': 'Verdejo', 'type': 'White',
             'description': 'A Spanish white wine with flavors of citrus, melon, and herbs.'},
            {'name': 'Nebbiolo', 'type': 'Red',
             'description': 'An Italian red wine with flavors of red berries, roses, and tar.'},
            {'name': 'Trebbiano', 'type': 'White',
             'description': 'An Italian white wine with flavors of citrus, apple, and almond.'},
            {'name': 'Cabernet Franc', 'type': 'Red',
             'description': 'A red wine with flavors of red berries, herbs, and green pepper.'},
            {'name': 'Grüner Veltliner', 'type': 'White',
             'description': 'An Austrian white wine with flavors of citrus, white pepper, and green apple.'},
            {'name': 'Sangiovese', 'type': 'Red',
             'description': 'An Italian red wine with flavors of cherry, plum, and leather.'},
            {'name': 'Vouvray', 'type': 'White',
             'description': 'A French white wine made from Chenin Blanc with flavors of apple, honey, and minerals.'},
            {'name': 'Dolcetto', 'type': 'Red',
             'description': 'An Italian red wine with flavors of dark berries, violet, and almond.'},
            {'name': 'Verdejo', 'type': 'White',
             'description': 'A Spanish white wine with flavors of citrus, melon, and herbs.'},
            {'name': 'Aglianico', 'type': 'Red',
             'description': 'An Italian red wine with flavors of dark berries, chocolate, and earth.'},
            {'name': 'Falanghina', 'type': 'White',
             'description': 'An Italian white wine with flavors of citrus, pear, and floral notes.'},
            {'name': 'Txakoli', 'type': 'White',
             'description': 'A Spanish white wine with flavors of green apple, lime, and saline minerality.'},
            {'name': 'Verdicchio', 'type': 'White',
             'description': 'An Italian white wine with flavors of citrus, almond, and herbs.'},
            {'name': "Nero d'Avola", 'type': 'Red',
             'description': 'An Italian red wine with flavors of dark berries, plum, and spice.'},
            {'name': 'Sagrantino', 'type': 'Red',
             'description': 'An Italian red wine with flavors of blackberry, plum, and tobacco.'},
            {'name': 'Arneis', 'type': 'White',
             'description': 'An Italian white wine with flavors of citrus, pear, and almond.'},
        ]

        for wine_info in wines_data:
            Wine.objects.create(name=wine_info['name'], type=wine_info['type'], description=wine_info['description'])

        self.stdout.write(self.style.SUCCESS('Successfully populated the database with wine data.'))
