# Generated by Django 5.0.4 on 2024-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineLabsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
