# Generated by Django 5.0.4 on 2024-04-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WineLabsApp', '0002_wine_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='image_url',
            new_name='image',
        ),
    ]
