# Generated by Django 5.0.4 on 2024-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineLabsApp', '0003_rename_image_url_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(upload_to='images/wines/'),
        ),
    ]
