# Generated by Django 5.0.4 on 2024-04-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineLabsApp', '0004_alter_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(upload_to='static/images/wines/'),
        ),
    ]
