# Generated by Django 5.0.4 on 2024-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineLabsApp', '0006_alter_wine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='keywords',
            field=models.ManyToManyField(to='WineLabsApp.keyword'),
        ),
    ]
